---
title: "Lab 06 - Conveying the right message through visualisation"
author: [TEAM NAME]
output: github_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```


### Exercise 1

```{r create-data}
df <- tribble(
  ~date, ~mask, ~no_mask,
  "12/7/2020", 26, 10,
  "13/7/2020", 20, 9,
  "14/7.2020", 20.2, 9.5,
  "15/7/2020", 20.5, 9.8,
  "16/7/2020", 19.8, 9.9,
  "17/7/2020", 19.8, 9.6,
  "18/7/2020", 20.2, 9.2,
  "19/7/2020", 20, 9.1,
  "20/7/2020", 20.5, 8.6,
  "21/7/2020", 21.5, 8.6,
  "22/7/2020", 19.8, 8.7,
  "23/7/2020", 19.8, 8.5,
  "24/7/2020", 20.2, 9.8,
  "25/7/2020", 19, 9.9,
  "26/7/2020", 19.7, 10.1,
  "27/7/2020", 17, 9.5,
  "28/7/2020", 16.2, 9.5,
  "29/7/2020", 16.4, 9.6,
  "30/7/2020", 16.5, 10,
  "31/7/2020", 16, 8.8,
  "01/8/2020", 16.2, 9,
  "02/8/2020", 15.8, 8.8,
  "03/8/2020", 15.9, 9.2
)
df <- pivot_longer(df,
  cols = c(mask, no_mask),
  names_to = "mask",
  values_to = "count")

df <- mutate(df, date = dmy(date))
```


### Exercise 2

```{r better-viz}
ggplot(df, aes(x = date, y = count, group = mask, color = mask)) +
      geom_line() +
      theme(axis.text.x = element_text(angle = 90)) +
      scale_x_date(date_breaks = "1 day") +
  labs(title = "Kansas COVID-19 7-Day Rolling Average of Daily Cases/Per 100K Population",
       subtitle = "Mask Counties Vs. No-Mask Mandate Counties",
       ylab = "Average of Daily Cases/Per 100K Population")
```


### Exercise 3

The ralationship between the two set of values can be compared more clearly.


### Exercise 4

The number of cases in the counties wearing musk is decreasing but always higher than population aren't wearing musk.
